let
Source = Table.FromRecords({[A=12,B=1], [A=24,B=2], [A=5,B=1], [A=12,B=3], [A=1,B=1]}),
#”Changed Type” = Table.TransformColumnTypes(Source,{{“A”, Int64.Type}, {“B”, Int64.Type}}),
#”Replaced Value” = Table.ReplaceValue(#”Changed Type”, each [A],each [A]/[B],Replacer.ReplaceValue,{“A”})
in
#”Replaced Value”
